package com.slc.afea.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.slc.afea.database.CollectRecord;

import com.slc.afea.database.CollectRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectRecordDaoConfig;

    private final CollectRecordDao collectRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectRecordDaoConfig = daoConfigMap.get(CollectRecordDao.class).clone();
        collectRecordDaoConfig.initIdentityScope(type);

        collectRecordDao = new CollectRecordDao(collectRecordDaoConfig, this);

        registerDao(CollectRecord.class, collectRecordDao);
    }
    
    public void clear() {
        collectRecordDaoConfig.clearIdentityScope();
    }

    public CollectRecordDao getCollectRecordDao() {
        return collectRecordDao;
    }

}
